### ISSUE TITLE
OnAudioTrackUnderrun(int, long, long) is missing

### ISSUE THREAD

**Issue by dspacey89** [martijn00/ExoPlayerXamarin#12]
Hi,

I keep getting the following when I compile the zip folder under 1.5.3. 1.5.2 works fine. 

VideoPlayer' does not implement interface member 'MediaCodecAudioTrackRenderer.IEventListener.OnAudioTrackUnderrun(int, long, long)

I confirmed that this method is not implemented in VideoPlayer.

**Comment by martijn00** [comment]
I am not seeing this error. Can you provide a sample to reproduce this?

**Comment by dspacey89** [comment]
I compiled it using VS2015 on Win10. I'll try it again later today and get back with you.

**Comment by dspacey89** [comment]
I'm still getting this error. I even tried Xamarin Studio. If you look at VideoPlayer, it implements MediaCodecAudioTrackRenderer.IEventListener which has OnAudioTrackUnderrun method. This method is missing in VideoPlayer. Maybe it has not been checked in to source control?

**Comment by martijn00** [comment]
I thought you ment in the library, but i see that it is in the sample. Maybe @MKuckert can take a look?

**Comment by MKuckert** [comment]
This pull request fixes the problem: https://github.com/martijn00/ExoPlayerXamarin/pull/14
