### ISSUE TITLE
Operator '==' cannot be applied to operands of type 'string' and 'int'

### ISSUE THREAD

**Issue by dspacey89** [martijn00/ExoPlayerXamarin#13]
Getting this error in PlayerActivity.cs

        private static string BuildTrackIdString(MediaFormat format)
		{
			return format.TrackId == MediaFormat.NoValue
				? ""
				: String.Format(Locale.Us, " (%d)", format.TrackId);
		}

Looks like TrackId and NoValue are of different types.

**Comment by MKuckert** [comment]
This merge request fixes the problem: https://github.com/martijn00/ExoPlayerXamarin/pull/14
