### ISSUE TITLE
Crash while streaming live HLS

### ISSUE THREAD

**Issue by piandcache** [martijn00/ExoPlayerXamarin#17]
Keep getting the attached native fail. Running only on API 16 (4.1.2) Nexus 7 (WIFI)

Not sure what it is. 

[[EventLogger] videoFormat [15.65, 1, 0].txt](https://github.com/martijn00/ExoPlayerXamarin/files/103575/EventLogger.videoFormat.15.65.1.0.txt)

**Comment by martijn00** [comment]
Please check again on the latest version
