### ISSUE TITLE
Monodroid support 

### ISSUE THREAD

**Issue by jonathanantoine** [martijn00/ExoPlayerXamarin#181]
## 💬 Questions and Help

Thanks for this repo.
Is there plan to support monodroid  ? The package seems to provide netcoreapp only.

Regards.

**Comment by ArchangelWTF** [comment]
It does! You just have to select prereleases to see it (The latest that's target monoandroid should be [2.19.1-xamarin1](https://www.nuget.org/packages/Xam.Plugins.Android.ExoPlayer/2.19.1-xamarin1))

**Comment by jonathanantoine** [comment]
Arf this good old dashed suffix that is considered as a pre-release by Nuget. Thanks a lot, its working !
