### ISSUE TITLE
Update sample code so it runs for 1.5.4

### ISSUE THREAD

**Issue by adrianknight89** [martijn00/ExoPlayerXamarin#19]
I can't compile and run the sample code in VS2015.

'VideoPlayer' does not implement interface member 'DashChunkSource.IEventListener.OnAvailableRangeChanged(int, ITimeRange)'

**Comment by adrianknight89** [comment]
@MKuckert

**Comment by nunohorta** [comment]
same here. I can't get my project to compile after the last update

**Comment by martijn00** [comment]
This will be fixed by @bspinner soon!
