### ISSUE TITLE
Retain played media in buffer unless space is actually needed to buffer further ahead

### ISSUE THREAD

**Issue by pottabathini** [martijn00/ExoPlayerXamarin#21]
@martijn00 we are using ExoPlayer to play .MP4 files which is playing very well but there is a problem with seek. When we backward the seek bar it is not retain the buffered content.

The same issue already reported in original Android Exoplayer @ [https://github.com/google/ExoPlayer/issues/896](url) and it got solved in the latest version.

Could you please update the bindings for us. We are relaying on this media player to play the .Mp4 Videos but with out retain buffered data  we can not go for a release.

Please update the bindings. Thank you

**Comment by martijn00** [comment]
Thanks for notifying. I'll try to update this as soon as i have time.

**Comment by martijn00** [comment]
Bindings are updated to 1.5.8
