### ISSUE TITLE
Mistake on documentation

### ISSUE THREAD

**Issue by SergioZgz** [martijn00/ExoPlayerXamarin#25]
Hi, 

I think you should change Documentation on main page, MediaCodecAudioTrackRenderer dont accept 2 params, the correct one could be for example:

TrackRenderer aRenderer = MediaCodecAudioTrackRenderer(sampleSource, MediaCodecSelector.Default); 

Thanks for your work :)

**Comment by martijn00** [comment]
Thanks! I've corrected this. A full sample is also available for more insights.
