### ISSUE TITLE
Any thought on turning this into a full fledged control

### ISSUE THREAD

**Issue by ravensorb** [martijn00/ExoPlayerXamarin#26]
Your samples are awesome!  Any thought to moving them into something like a ControlRenderer so they can be leveraged a little easier for developer new to the ExoPlayer?

**Comment by martijn00** [comment]
I haven't looked into making something like that, but i would take a pull request if you have something!

**Comment by adrianknight89** [comment]
I'd love to see a control as well. For starters like me, this is advanced stuff!!

**Comment by martijn00** [comment]
You can now use my https://github.com/martijn00/XamarinMediaManager with Exoplayer as media backend.
