### ISSUE TITLE
Implements the OkHttp extension

### ISSUE THREAD

**Issue by jonhbala** [martijn00/ExoPlayerXamarin#27]
Hi,

I'm try to play shoutcast AAC stream, but works only in android API  20+.

I search this bug in ExoPlayer repositorie and I find this issue: https://github.com/google/ExoPlayer/issues/1157#issuecomment-173125170 and I got success when I build Java APP with this `new OkHttpDataSource(client, "ExoPlayer", null, null)` ´part of OkHttp extension...
I try binding ths class and re code in C# but I fail...

Can you implement this? Or say what I do? 

Thanks so much!

**Comment by martijn00** [comment]
Done in https://github.com/martijn00/ExoPlayerXamarin/commit/441eab0cd308906200fa7796872c43c435199fe2
