### ISSUE TITLE
Wav support

### ISSUE THREAD

**Issue by truthz03** [martijn00/ExoPlayerXamarin#28]
Hi,

today I downloaded the version 1.5.8 from your great project but I have a big problem.
It seems that the WavExtractor is missing. If I extract the aar file from your repository there is a WavExtractor.class inside the "com\google\android\exoplayer\extractor\wav\" folder but there is no c# class for that.
Is there a reason why the WavExtractor is missing?

**Comment by martijn00** [comment]
Could you give this a try with the 2.x version of ExoPlayer?
