### ISSUE TITLE
Namespaces do not exist

### ISSUE THREAD

**Issue by CMyhillWorkDev** [martijn00/ExoPlayerXamarin#3]
When I build the solution I get the following errors;

1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Chunk.Chunk.cs(9,112,9,118): error CS0234: The type or namespace name 'Loader' does not exist in the namespace 'Com.Google.Android.Exoplayer.Upstream' (are you missing an assembly reference?)
1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Chunk.MultiTrackChunkSource.cs(9,110,9,119): error CS0234: The type or namespace name 'ExoPlayer' does not exist in the namespace 'Com.Google.Android.Exoplayer' (are you missing an assembly reference?)
1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.TrackRenderer.cs(9,111,9,120): error CS0234: The type or namespace name 'ExoPlayer' does not exist in the namespace 'Com.Google.Android.Exoplayer' (are you missing an assembly reference?)
1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Parser.Webm.DefaultWebmExtractor.cs(13,130,13,147): error CS0234: The type or namespace name 'IEbmlEventHandler' does not exist in the namespace 'Com.Google.Android.Exoplayer.Parser.Webm' (are you missing an assembly reference?)
1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Upstream.DataSourceStream.cs(9,121,9,127): error CS0234: The type or namespace name 'Loader' does not exist in the namespace 'Com.Google.Android.Exoplayer.Upstream' (are you missing an assembly reference?)
1>W:\ExoPlayerXamarin-master\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Text.Ttml.TtmlSubtitle.cs(31,71,31,79): error CS0234: The type or namespace name 'TtmlNode' does not exist in the namespace 'Com.Google.Android.Exoplayer.Text.Ttml' (are you missing an assembly reference?)

**Comment by martijn00** [comment]
This is fixed in the latest updates
