### ISSUE TITLE
How to disable the HW acceleration ?

### ISSUE THREAD

**Issue by tombby11** [martijn00/ExoPlayerXamarin#30]
Hello , 
When I play some videos on my machine with my app that uses ExoplayerXamarin, I get some green bar on top . or sometimes lagging . 
I know the problem is with the HW acceleration . So is there a way to turn it off and use the software decoders ?

**Comment by martijn00** [comment]
This should be available now in version 1.5.10 by using `getDecoderInfos`

**Comment by tombby11** [comment]
I have the latest nuget installed now , but cannot find the method
