### ISSUE TITLE
Update bindings to 2.0

### ISSUE THREAD

**Issue by martijn00** [martijn00/ExoPlayerXamarin#32]
Initial work is done in https://github.com/martijn00/ExoPlayerXamarin/tree/exoplayer2

**Comment by jmyrland** [comment]
Awesome work on this @martijn00, thanks!

When is this expected to be available in Nuget?

**Comment by martijn00** [comment]
I still have some bugs to solve before i can put this up on Nuget. Any help would be appreciated!

**Comment by martijn00** [comment]
You could help updating the sample to the official demo of 2.0: https://github.com/martijn00/ExoPlayerXamarin/tree/exoplayer2/Samples/Official%20Demo

**Comment by rraallvv** [comment]
Does anyone know what version of the package should I have to run the samples?
I tried just downloading the sample folder "Official Demo" and installing the NuGet package from VS but I'm getting lots of errors when building. For instance these interfaces used by `EventLogger` are missing:
```
IPlayerEventListener,
IAudioRendererEventListener,
IVideoRendererEventListener,
IAdaptiveMediaSourceEventListener
```
