### ISSUE TITLE
 MetadataRenderer.IOutput dont include onMetadata Member

### ISSUE THREAD

**Issue by bubavanhalen** [martijn00/ExoPlayerXamarin#38]
I can't use the  `MetadataRendere.IOutput` Interface, it doesn't compile during the C# version doesn't have the event `OnMetadata` included which gives an error while compiling in the xxx.Java file.

![image](https://cloud.githubusercontent.com/assets/11610646/19870183/cc2bd92e-9faf-11e6-887b-779b6dc55eef.png)

**Comment by martijn00** [comment]
This is fixed in 2.1.1
