### ISSUE TITLE
v2.1.1 Update

### ISSUE THREAD

**Issue by ilkayilknur** [martijn00/ExoPlayerXamarin#40]
Hi,
Do you have any plans to update bindings to v2.1.1 release ? We need to implement this change. https://github.com/google/ExoPlayer/commit/7bbe213e578a3f2de8bc7e9b4886c8d5e74a8dda

**Comment by martijn00** [comment]
Yes, i will work on this as soon as i have time.

**Comment by martijn00** [comment]
Addressed in https://github.com/martijn00/ExoPlayerXamarin/commit/2ae820da2e6319fd3228d3dadbf8655a048ecfc4
