### ISSUE TITLE
ExoPlayer can't play Vimeo videos

### ISSUE THREAD

**Issue by ebal155** [martijn00/ExoPlayerXamarin#44]
When I try to play a video hosted on Vimeo, the player throws a java.security.cert.CertificateException (this is Exoplayer 1). It used to work before, any idea why the Vimeo certificates are not being recognised? I'm using the DefaultUriDataSource implementation (which uses HttpsURLConnection).

**Comment by martijn00** [comment]
This is a sort of question that belongs on Stackoverflow, as this goes into implementation details and not on the library itself.
