### ISSUE TITLE
Dim Video On Some Android Devices

### ISSUE THREAD

**Issue by nonlin** [martijn00/ExoPlayerXamarin#47]
For some reason so far on an Android 6.0 Samsung Galaxy 6 the video's brightness is normal but on Android 6.0 for an LG-G4, Android 7.1.1 Pixel and 6P the video is dim. Both have the same code and the same video source. 

It is quite confusing. I suspect it is an issue with ExoPlayer.

**Comment by martijn00** [comment]
Please take this up with Google ExoPlayer
