### ISSUE TITLE
Error when playing mkv files over 4GB

### ISSUE THREAD

**Issue by smedasn** [martijn00/ExoPlayerXamarin#48]
The exeption I get is the following.

`07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): Source error.
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): java.io.EOFException
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:95)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:104)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:127)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:340)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-02 21:46:02.669 E/ExoPlayerImplInternal(10387): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
`

I think this issue is related to this issue. https://github.com/google/ExoPlayer/issues/641

Are the current exoplayer jars binded in your nuget ExoPlayerXamarin package?

Btw. Thank you very much for the xamarin bindings!

**Comment by martijn00** [comment]
The latest update is out and should fix this.
