### ISSUE TITLE
Method not found 'Android.Runtime.JNIEvn.CallStaticOjbectMethod

### ISSUE THREAD

**Issue by Shirley923** [martijn00/ExoPlayerXamarin#5]
Hi Martijn,
       I download your code, and running with Android 5.0, it throw error "Method not found 'Android.Runtime.JNIEvn.CallStaticOjbectMethod" on line "mediaPlayer = Com.Google.Android.Exoplayer.ExoPlayerFactory.NewInstance(1)", I'm not sure how to resolve the problem, any suggestions?
Thanks,
Shirley

**Comment by martijn00** [comment]
Thanks for reporting! I'll look into this.

**Comment by MKuckert** [comment]
Just checked the source on an Android 5.0.1 AVD - everything works good...

@Shirley923 Can you provide more informations about the device you used?

**Comment by MKuckert** [comment]
@martijn00 I think we can close this then...
