### ISSUE TITLE
Missing binding method on 2.5.1?

### ISSUE THREAD

**Issue by jesuscoz** [martijn00/ExoPlayerXamarin#50]
Is SimpleExoPlayer binding class missing the Prepare methods?:

```
public void Prepare(MediaSource mediaSource);

public void Prepare(MediaSource mediaSource, boolean resetPosition, boolean resetState);
```

**Comment by jesuscoz** [comment]
Looks like the problem is caused by this exclusion:

`<remove-node path="/api/package[@name='com.google.android.exoplayer2']/interface[@name='ExoPlayer']" />`

binding exclude methods of the interface

**Comment by martijn00** [comment]
New packages are online.
