### ISSUE TITLE
java.lang.IllegalArgumentException  at android.media.MediaCodec.native_setSurface

### ISSUE THREAD

**Issue by andreabonassi** [martijn00/ExoPlayerXamarin#56]
Good morning i have this exception when i play a .mp4 video from sdcard:

`09-19 15:07:08.083 I/MediaCodec(17696): [OMX.Freescale.std.video_decoder.avc.v3.hw-based] setting surface generation to 18120706
09-19 15:07:08.085 D/SurfaceUtils(17696): set up nativeWindow 0x962d3d08 for 1024x576, color 0x13, rotation 0, usage 0x8002900
09-19 15:07:08.085 E/ACodec  (17696): new surface holds onto more buffers (1) than planned for (0)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): Internal runtime error.
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): java.lang.IllegalArgumentException
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at android.media.MediaCodec.native_setSurface(Native Method)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1797)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:743)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:360)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:327)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessagesInternal(ExoPlayerImplInternal.java:849)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at android.os.Looper.loop(Looper.java:148)
09-19 15:07:08.086 E/ExoPlayerImplInternal(17696): 	at android.os.HandlerThread.run(HandlerThread.java:61)`

This is my OnCreate functions:

`protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);

            DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            AdaptiveTrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            player = ExoPlayerFactory.NewSimpleInstance(this, trackSelector);

            simpleExoPlayerView = (SimpleExoPlayerView)FindViewById(Resource.Id.player_view);

            simpleExoPlayerView.UseController = (true);
            simpleExoPlayerView.RequestFocus();

            simpleExoPlayerView.Player = (player);

            string urimp4 = "/mnt/am_sd2/VideoPubblicitari/CocaCola.mp4"; //upload file to device and add path/name.mp4
            Uri mp4VideoUri = Uri.Parse(urimp4);

            //Measures bandwidth during playback. Can be null if not required.
            DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();
            //Produces DataSource instances through which media data is loaded.
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.GetUserAgent(this, "ExoPlayerExample"), bandwidthMeterA);
            //Produces Extractor instances for parsing the media data.
            DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

            //This is the MediaSource representing the media to be played:
            //FOR SD CARD SOURCE
            IMediaSource videoSource = new ExtractorMediaSource(mp4VideoUri, dataSourceFactory, extractorsFactory, null, null);

            //FOR LIVESTREAM LINK:
            //        MediaSource videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, 1, null, null);

            loopingSource = new LoopingMediaSource(videoSource);

            // Prepare the player with the source.
            player.Prepare(loopingSource);
            player.AddListener(this);
            player.SetVideoDebugListener(this);
            player.PlayWhenReady = true;

        }`

Where is the problem?

**Comment by SimpsOff** [comment]
It looks like this may be similar to the issue posted here:
https://github.com/google/ExoPlayer/issues/2703

A newer version of the library may help, otherwise you can try and do what was suggested in the other thread and set up a `SurfaceManager` like they posted, it might help with the issue.

**Comment by martijn00** [comment]
Maybe try to use the new 2.7.2?
