### ISSUE TITLE
Support ExoPlayer r1.4.2

### ISSUE THREAD

**Issue by adamfisher** [martijn00/ExoPlayerXamarin#6]
This is a great library! Any idea when support for r1.4.2 might be available on Nuget? It looks like a ton of new capability and quality improvements have happened since 1.3.3. Most notable being the automatic format detection for regular container formats.

https://github.com/google/ExoPlayer/blob/dev/RELEASENOTES.md#r142

**Comment by adamfisher** [comment]
Attempted to replace the existing jar library but found some incompatibilities.

```
Severity	Code	Description	Project	File	Line
Error		The type or namespace name 'WebvttCue' does not exist in the namespace 'Com.Google.Android.Exoplayer.Text.Webvtt' (are you missing an assembly reference?)	ExoPlayer	D:\Projects\ExoPlayerXamarin\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Text.Webvtt.WebvttSubtitle.cs	31
Error		'SubripParser' does not implement interface member 'ISubtitleParser.Parse(Stream, string, long)'	ExoPlayer	D:\Projects\ExoPlayerXamarin\ExoPlayer\obj\Debug\generated\src\Com.Google.Android.Exoplayer.Text.Subrip.SubripParser.cs	9
```

**Comment by martijn00** [comment]
I can look into it, but i am not sure when i have time. I would accept a pull request if you can make one.

**Comment by martijn00** [comment]
i've updated to 1.4.2 but it is untested.
