### ISSUE TITLE
Sample doesn't seem to build

### ISSUE THREAD

**Issue by kevleyski** [martijn00/ExoPlayerXamarin#61]
### Steps to reproduce :scroll:

1. Build ExoPlayer project
2. then ExoPlayer (develop) sample

### Expected behavior :thinking:
Build run/test

### Actual behavior :bug:
Compile failures around ExoPlayer.Demo::EventLogger.cs

	internal sealed class EventLogger : Object, IPlayerEventListener, IAudioRendererEventListener,
		IVideoRendererEventListener, IAdaptiveMediaSourceEventListener,
		ExtractorMediaSource.IEventListener, DefaultDrmSessionManager.IEventListener,
		MetadataRenderer.IOutput

ExoPlayerXamarin/Samples/Official Demo/EventLogger.cs(68,68): Error CS0246: The type or namespace name 'IAudioRendererEventListener' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (ExoPlayer.Demo)
ExoPlayerXamarin/Samples/Official Demo/EventLogger.cs(3,3): Error CS0246: The type or namespace name 'IVideoRendererEventListener' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (ExoPlayer.Demo)
ExoPlayerXamarin/Samples/Official Demo/PlayerActivity.cs(65,65): Error CS0535: 'PlayerActivity' does not implement interface member 'IPlayerEventListener.OnTimelineChanged(Timeline, Object, int)' (CS0535) (ExoPlayer.Demo)
ExoPlayerXamarin/Samples/Official Demo/EventLogger.cs(46,46): Error CS0535: 'EventLogger' does not implement interface member 'IPlayerEventListener.OnTimelineChanged(Timeline, Object, int)' (CS0535) (ExoPlayer.Demo)

### Configuration :wrench:

**Version:** 2.x

**Platform:** 
- [ ] :robot: Android

**Comment by aixiaozi** [comment]
The sample use Xam.Plugins.Android.Exoplyer 2.5.2, so you could download sample from here: https://github.com/martijn00/ExoPlayerXamarin/releases

Then, download the 2.5.2 Source code,  I test on my side, it works fine.

**Comment by kevleyski** [comment]
Smashing! thanks
