### ISSUE TITLE
Video format in .m3u8

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [martijn00/ExoPlayerXamarin#62]
Hello, how do I play .m3u8 videos with this library?
(Sorry my bad english)

**Comment by nunohorta** [comment]
The samples in this library can play HLS just fine, you just need to pass the url.

This is a binding library from Google's Exoplayer and you'll find hundreds of tutorials/posts on how to play HLS. You just need to look at the code in java and convert it to C# which is fairly simple.

**Comment by andersonvieiragomeslopes** [comment]
I tested, but it does not work, it does not run

[http://prntscr.com/jmv0y1](url)

Code: 

`<local:VideoPlayer SourceUrl="https://d1h84if288zv9w.cloudfront.net/7dias/0be3_135.stream/playlist.m3u8" />`

PS: You're not seeing wrong, it's **xamarin forms** (Android) :), any idea what I can do to run video in **.m3u8**? Only **.mp4** is working.
