### ISSUE TITLE
Update samples to work with 2.8.0

### ISSUE THREAD

**Issue by scxp** [martijn00/ExoPlayerXamarin#63]
On #61, it's mentioned that the samples work with 2.5.2 which Google released in September of last year. Can you update the samples so they work with 2.8.0?

**Comment by martijn00** [comment]
I would accept a pull request to update this. Maybe @MKuckert or @bspinner can help out?

**Comment by bspinner** [comment]
@martijn00 Looks like you've made some changes already. Is this still an issue?

**Comment by martijn00** [comment]
@bspinner yes, the samples are still not up to date. The other things compile fine now.
