### ISSUE TITLE
(question) Custom patching the ExoPlayer aar

### ISSUE THREAD

**Issue by kevleyski** [martijn00/ExoPlayerXamarin#66]
I need to add a custom patch to 
https://github.com/martijn00/ExoPlayerXamarin/blob/develop/ExoPlayer/Jars/exoplayer-2.8.1.aar

I was wondering do you build this yourself or is it from a release? (I thought the aars for ExoPlayer were separed into core and extensions? Rather than a combined aar)

What's best way to support custom variations in your option? No API changes I'm just testing a bug fix to a PR I have with ExoPlayer library itself

**Comment by martijn00** [comment]
Exoplayer is indeed split up. The .aar file is just a forwarder to the different dependencies, to not break compatibility. I get the files from Bintray.

You need to compile the fix yourself, and make a new build with my source code and hook that up into your project.

**Comment by kevleyski** [comment]
No worries, appreciated
