### ISSUE TITLE
Android ExoPlayer Version 2.8.3 - 'Java.Lang.Reflect.InvocationTargetException' was thrown. 

### ISSUE THREAD

**Issue by haohighview** [martijn00/ExoPlayerXamarin#76]
Android ExoPlayer Version 2.8.3
{Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.IncompatibleClassChangeError: The method 'void com.google.ads.interactivemedia.v3.api.ImaSdkSettings.setPlayerType(java.lang.String)' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.google.android.exoplayer2.ext.ima.ImaAdsLoader' appears in /data/app/com.highviewsoft.bopoda-1/base.apk)

**Comment by martijn00** [comment]
Can you make a sample repo so i can test this?

**Comment by martijn00** [comment]
Dependency is updated in https://github.com/martijn00/ExoPlayerXamarin/commit/f9eac785942c66f95308ef6a6b2e5ab420428882
