### ISSUE TITLE
Android Minimum version >= 26

### ISSUE THREAD

**Issue by AnonymusRaccoon** [martijn00/ExoPlayerXamarin#77]
Hello, i've seen that the last release need the minimum MonoDroid version to be Oreo or newer. Why this restriction ? I've looked on the exoplayer website and they support android version greater than Lolipop with all the features. Is this an intended behavior and if so, why ? 

PS: i want to upgrade because if've found a bug on the 2.8.8 version and was wondering if it has been solved in the last version. You can't play audio of file in local storage if there is a # (hash) in the filename or path.

Thanks for reading.

**Comment by martijn00** [comment]
Oreo is not the minimum version, but the compile target. You can still set lolipop as minimum target just as they say on the website.

The latest version only works with https://github.com/martijn00/ExoPlayerXamarin/issues/74#issuecomment-438425105
