### ISSUE TITLE
Documentation recommendation

### ISSUE THREAD

**Issue by Ruud-cb** [martijn00/ExoPlayerXamarin#80]
## 🏗 Enhancement Proposal

Hi,

I would really suggest adding this documentation to your Readme: https://codelabs.developers.google.com/codelabs/exoplayer-intro/#0

The documentation currently pointed to is a bit broad and not down to earth on what steps to take.
It at least would have saved me some time when starting with this.

Also the "Exoplayer.Droid sample app" can't be found anywhere within this repo. 

After all: Great repo! A bit unfortunate that I have to go for v2.8.8 instead of 2.9.0 because switching to VS2019 seems to early at this stage.

**Comment by martijn00** [comment]
You need to set the dex compiler to d8 in the android options so java 1.8 support is enabled.
