### ISSUE TITLE
Exoplayer Integration with Xamarin 

### ISSUE THREAD

**Issue by ShllyBhgal** [martijn00/ExoPlayerXamarin#82]
Hi Folks,

I am trying to Integrate Exoplayer with Xamarin.Android but somehow i am able to play small size video which are located at cdn servers but for large file exoplayer goes to the ideal state and does not play video.

I have also tried Exoplayerdash for mpd file using streaming servers but still not able to play large size videos in xamarin. Please help me understand where I am lacking.

Regards,
Shelly

**Comment by martijn00** [comment]
Please post questions on StackOverflow.
