### ISSUE TITLE
Java.Lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by leeapted** [martijn00/ExoPlayerXamarin#85]
I'm getting a runtime error when using ExoPlayer with a RTMP source.

Java.Lang.NoClassDefFoundError: Failed resolution of: Lnet/butterflytv/rtmp_client/RtmpClient;

Any ideas on how to resolve this?

(I'm using 2.8.8 since I do not have Visual Studio 2019 installed.)

Thank you!

**Comment by martijn00** [comment]
Please use the issue templates
