### ISSUE TITLE
Navigation with custom renderer 

### ISSUE THREAD

**Issue by tonyyyrocks39** [martijn00/ExoPlayerXamarin#86]
Hi,

I have a listview in mainpage,when i click listview it goes to 2nd page where it has a videoplayer,so the problem is how to release the player properly,as currently _player is equals to null always ,multiple videos are played.

 protected override void OnElementChanged(ElementChangedEventArgs<VideoPlayer> e)
        {
            base.OnElementChanged(e);
            
            if (_player == null)
            {
                InitializePlayer();
            }
            

            Play();
        }

      
        private void InitializePlayer()
        {
           
            trackSelector = new DefaultTrackSelector();
            
            _player = ExoPlayerFactory.NewSimpleInstance(Context,trackSelector);
            _player.PlayWhenReady = true;
            _playerView = new SimpleExoPlayerView(Context) { Player = _player };
            SetNativeControl(_playerView);
            SetBackgroundColor(Android.Graphics.Color.Green);
        }

        private void Play()
        {
       
                Uri sourceUri = Uri.Parse(Element.SourceUrl);
                var mediaUri = Android.Net.Uri.Parse(Element.SourceUrl);
                var userAgent = Util.GetUserAgent(Context, "App1");
                var defaultHttpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent);
                var defaultDataSourceFactory = new DefaultDataSourceFactory(Context, null, defaultHttpDataSourceFactory);
                var extractorMediaSource = new ExtractorMediaSource(mediaUri, defaultDataSourceFactory, new DefaultExtractorsFactory(), null, null);
                _player.Prepare(extractorMediaSource);
                _player.AddListener(this);

        }

**Comment by martijn00** [comment]
Not sure what you mean with this. Please open an issue with a better description.
