### ISSUE TITLE
State Constants (Ex. ExoPlayer.StateReady) are marked deprecated

### ISSUE THREAD

**Issue by aweck** [martijn00/ExoPlayerXamarin#87]
Why are these deprecated?  I need to use them for a PlayerExentListener

**Comment by aweck** [comment]
Ah, they have been moved to Player.

**Comment by mr5z** [comment]
This should be reopened.

`OnPlayerStateChanged(bool playWhenReady, int playbackState)`

Should be changed to **enum** instead of **int**
