### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by bsysop** [martijn00/ExoPlayerXamarin#9]
Maybe this is really stupid, but, have some chance to do this work for iOS?

**Comment by martijn00** [comment]
ExoPlayer is a component made by Google and will only work on Android. If you are looking for a mediaplayer for iOS i would recommend my other library: https://github.com/martijn00/XamarinMediaManager/blob/master/MediaManager/MediaManager.Plugin.iOSUnified/MediaManagerImplementation.cs

**Comment by bsysop** [comment]
Great, thank you @martijn00
