### ISSUE TITLE
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)

### ISSUE THREAD

**Issue by kishor010** [martijn00/ExoPlayerXamarin#93]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Use d8 as compiler. Also see other closed issues.

**Comment by kishor010** [comment]
How to use d8 compiler.
@martijn00 
Thanks for reply.
Is this the solution ?

**Comment by martijn00** [comment]
Use VS2019 16.2 or higher. Open Android properties > Android options > Dex compiler > select d8.
