### ISSUE TITLE
SsMediaSource is not working even though URL is proper. (http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8)

### ISSUE THREAD

**Issue by kishor010** [martijn00/ExoPlayerXamarin#94]
VideoPlayerRenderer.cs(47,47): Warning CS0618: 'SsMediaSource.SsMediaSource(Uri, IDataSourceFactory, ISsChunkSourceFactory, Handler, IMediaSourceEventListener)' is obsolete: 'deprecated' (CS0618) (POC_VideoPlayer.Android).

ExoPlayerImplInternal] Source error.
[ExoPlayerImplInternal] com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
[ExoPlayerImplInternal] 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal] 	at java.lang.Thread.run(Thread.java:764)

**Comment by martijn00** [comment]
It's working fine for me in my plugin: https://github.com/martijn00/XamarinMediaManager

Please fill in the full issue template, or this issue will be closed.

**Comment by kishor010** [comment]
@martijn00 
I am not using MediaManager plugin.
I am working on Visual studio and I have created a video player for Android using "Exoplayer" SDK.

I am facing issue with deprecated method and eventListeners.
I checked samples but didn't get any one which can resolve my issue.

**Comment by kishor010** [comment]
@martijn00 
Can you please tell me
Why you closed this issue without any solution ?

**Comment by martijn00** [comment]
I refer back to: Please fill in the full issue template, or this issue will be closed.
